In [15]:
#Import libraries 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
from datetime import datetime, timedelta

In [16]:
#load and take a look 
df = pd.read_csv("C:\\Users\\mj\\Documents\\DA stuff\\Datasets\\archive\\online_retail_II.csv")
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  str
 1   StockCode    1067371 non-null  str
 2   Description  1062989 non-null  str
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  str
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 136.6 MB

In [17]:
df['Invoice'] =  df['Invoice'].str.replace(r"a-zA-Z","", regex=True)
df['Invoice'].str.contains(r"a-zA-Z","", regex=True)

df = df.dropna(subset=['Customer ID']).copy()
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

here we will isolate the transaction product codes from the operational non-standard product codes, now, there are non standard codes that still represent a transaction, like D(discounts) and cruk(a donation transaction) So i have to distinguish which are worth keeping for our cohort analysis.

In [ ]:
non_standard_codes = df[df['StockCode'].str.match(pat= '([a-z])', case=False) ]
unique_codes = non_standard_codes['StockCode'].unique()


customer_codes = ['POST','DOT', 'C2', 'D', 'M','SP1002','CRUK']
business_codes = ['TEST001', 'TEST002', 'BANK CHARGES', 'ADJUST2','DOT','ADJUST' ]

cleaned_codes = df[~df['StockCode'].isin(business_codes)] 

df = cleaned_codes.drop_duplicates()
df.duplicated().sum()
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [ ]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Revenue'] = df['Quantity'] * df['Price']
df.head()

reference_date = df['InvoiceDate'].max() + timedelta(days=1)
reference_date

rfm = df.groupby('Customer ID').agg({
    'InvoiceDate': lambda x: (reference_date - x.max()).days,
    'Invoice': 'count',
    'Revenue': 'sum'
})

             InvoiceDate  Invoice  Revenue
Customer ID
12346.0              326       36  -147.24
12347.0                2      222  4921.53
12348.0               75       51  2019.40
12349.0               19      180  4404.54
12350.0              310       17   334.40
...                  ...      ...      ...
18283.0                4      938  2664.90
18284.0              430       29   436.68
18285.0              661       12   427.00
18286.0              477       70  1188.43
18287.0               43      156  4177.89

[5922 rows x 3 columns]

In [23]:
rfm.rename( columns= {'InvoiceDate': 'Recency', 'Invoice':'Frecuency','Revenue':'Value'})
rfm.head()

             InvoiceDate  Invoice  Revenue
Customer ID
12346.0              326       36  -147.24
12347.0                2      222  4921.53
12348.0               75       51  2019.40
12349.0               19      180  4404.54
12350.0              310       17   334.40

In [20]:
df =

SyntaxError: invalid syntax (1581804619.py, line 1)

In [ ]:
#function to get

[        'POST',            'D',            'M',           'C2',
 'BANK CHARGES',      'TEST001',      'TEST002',         'PADS',
       'ADJUST',      'ADJUST2',       'SP1002',          'DOT',
         'CRUK']